routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard','dashboardController@index');
// Route::get('/kitchen','KitchenController@index');
Route::resource('kitchens', 'KitchenController');
Route::resource('restaurants', 'RestaurantController');
Route::resource('recipes', 'RecipeController');
Route::get('home','homeController@index');
Route::get('kitchen/{id}','kitchen_controller@kitchen')->name('kitchen');
Route::get('recipe/{id}','kitchen_controller@recipe')->name('recipe');
Route::post('search','homecontroller@search')->name('search');

Auth::routes();

app/restaurant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class restaurant extends Model
{
    public $timestamps=false;
}

app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\restaurant;
class RestaurantController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $restaurants=restaurant::all();
       return view ('backend.restaurants.index',compact('restaurants'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("backend.restaurants.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'title'=>'required | max:50 |min:5 ',

                'img'=>'required|image|mimes:jpeg,png,jpg,gif|max:2048'
            ]
              ) ;
             if($request->hasfile('img'))
             {
              $file=$request->file('img');
             $img=$this->uploadImg($file,"img/restaurants");

             }
             else
             {
               $img="no-image.png";
             }
            $restaurant=new restaurant();
            $restaurant->name=$request->title;
            $restaurant->img=$img;
            $restaurant->URL=$request->URL;
            $restaurant->kitchen_id=$request->kitchen_id;
            // $post->user_id=Auth::user()->id;
            $restaurant->save();

            // return redirect()->back();

            return redirect()->route('restaurants.index')->withmsg('post saved sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $restaurant=restaurant::find($id);
     return view("backend.restaurants.show",compact("restaurant"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $restaurants=restaurant::find($id);
      return view("backend.restaurants.edit",compact('restaurants'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'title'=>'required',
                'img'=>'required|image|mimes:jpeg,png,jpg,gif'
            ]
              ) ;
              if($request->hasfile('img'))
              {
               $file=$request->file('img');
              $img=$this->uploadImg($file,"img/restaurants");

              }
              else
              {
                $img="no-image.png";
              }

            $restaurant= restaurant::find($id);
            $restaurant->name=$request->title;
            $restaurant->img=$img;
            $restaurant->URL=$request->URL;
            $restaurant->kitchen_id=$request->kitchen_id;
            $restaurant->save();
            return redirect()->route('restaurants.index')->withmsg('post saved sucessfully');
    }
    public function uploadImg($img,$dir)
{
  $file=$img;

  $img_name=$file->getClientOriginalName();//name.jpg
  $ext=$file->getClientOriginalExtension();//jpg
  $image=time().$img_name;

  $file->move($dir,$image);
  return $image;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $restaurant=restaurant::find($id);
        $restaurant->delete();
        return redirect()->route('restaurants.index')->withmsg('restaurant deleted');
    }
}

resources/views/backend/restaurants/create.blade.php
@extends('layouts.app');

@section("title","restaurants")




@section("content")
<div class="container">



        <div class="row">

        <form method="post" action="{{url('/restaurants')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title">
                <label for="exampleFormControlSlect2" >URL</label>
                <input class="form-control" name="URL">
              </div>
              {{-- <div class="form-group">
                <label for="exampleFormControlTextarea1" >Content</label>
                <textarea class="form-control" name="content" rows="3"></textarea>
              </div> --}}
    <label for="exampleFormControlTextarea1">image</label>
    <input type="file" name="img">
        <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>


@endsection

resources/views/backend/restaurants/edit.blade.php
@extends('layouts.app');

@section("title","restaurants")



   
@section("content")
<div class="container">
          
        <div class="row">
    
        <form method="post" action="{{ route('restaurants.update',$restaurants->id)}}" enctype="multipart/form-data">
         

            @csrf @method("put")
            <div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title" value="{{$restaurants->name}}">
              </div>
              <div>
                <label for="exampleFormControlTextarea1">URL</label>
              <input type="form-control" name="URL" value="{{$restaurants->URL}}">
              </div>
              <div>
                <label for="exampleFormControlTextarea1">kitchen_id</label>
              <input type="form-control" name="kitchen_id" value="{{$restaurants->kitchen_id}}">
              </div>
              <label for="exampleFormControlTextarea1">image</label>
              <input type="file" name="img">
              
    
        <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>

    
@endsection

resources/views/backend/restaurants/index.blade.php
@extends('layouts.app');

@section("title","restaurants")




@section("content")
<div class="container">


     <div class="container-fluid">
      <a href="restaurants/create/">Add New Restaurants</a>
        <div class="row">

        @foreach ( $restaurants as $restaurant )

        <div class="card col-md-3" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><a href="restaurants/{{$restaurant->id}}">{{$restaurant->title}}</a></h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$restaurant->name}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">{{$restaurant->kitchen_id}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">{{$restaurant->URL}}</h6>
              <p class="card-text">{{$restaurant->img}}</p>
              <img src="{{asset('img/restaurants/'.$restaurant->img)}}" class=w-100 >
              @auth
              <a class="btn btn-primary" href="restaurants/{{$restaurant->id}}/edit" class="card-link">Edit</a>
  <form method="post" action="restaurants/{{$restaurant->id}}">
      @csrf @method("delete")
      <button type='submit' class="btn btn-danger">Delete</button>
  </form>
  @endauth
            </div>
          </div>



     @endforeach

        </div>
     </div>
</div>


@endsection

resources/views/backend/restaurants/show.blade.php
@extends('layouts.app');

@section("title","restaurants")



   
@section("content")
<div class="container">

      
    
   
  
        <div class="row">
    
        <div class="card col-md-12" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{$restaurant->title}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$restaurant->id}}</h6>
              <p class="card-text">{{$restaurant->name}}</p>
              <p class="card-text">{{$restaurant->URL}}</p>
              <p class="card-text">{{$restaurant->kitchen_id}}</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
            
        
    
 
     
        </div>
</div>

    
@endsection