routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard','dashboardController@index');
// Route::get('/kitchen','KitchenController@index');
Route::resource('kitchens', 'KitchenController');
Route::resource('restaurants', 'RestaurantController');
Route::resource('recipes', 'RecipeController');
Route::get('home','homeController@index');
Route::get('kitchen/{id}','kitchen_controller@kitchen')->name('kitchen');
Route::get('recipe/{id}','kitchen_controller@recipe')->name('recipe');
Route::post('search','homecontroller@search')->name('search');

Auth::routes();

app/recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class recipe extends Model
{
    public $timestamps=false;
    public function kitchen()
    {
        return $this->belongsTo("App\kitchen");
    }

  
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\recipe;

class Recipecontroller extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      // $recipes = recipe::paginate(12);
        $recipes=recipe::all();
       return view ('backend.recipes.index',compact('recipes'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $kitchens=\App\kitchen::all();
        return view("backend.recipes.create",compact('kitchens'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'title'=>'required',

                'image'=>'required',

                'about'=>'required',

                'ingredients'=>'required',

                'direction'=>'required',

            ]
              ) ;
             if($request->hasfile('image'))
             {
              $file=$request->file('image');
             $images=$this->uploadimages($file,"images");

             }
             else
             {
               $images="no-images.png";
             }
            $recipes=new recipe();
            $recipes->name=$request->title;
            $recipes->About=$request->about;
            $recipes->image=$images;
            $recipes->video=$request->video;
            $recipes->ingredients=$request->ingredients;
            $recipes->direction=$request->direction;
            $recipes->kitchen_id=$request->kitchen_id;

            // $post->user_id=Auth::user()->id;
            $recipes->save();

            // return redirect()->back();

            return redirect()->route('recipes.index')->withmsg('post saved sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $recipes=recipe::find($id);
     return view("backend.recipes.show",compact("recipes"));
    }

   

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $recipes=recipe::find($id);
        $kitchens=\App\kitchen::all();
        return view("backend.recipes.edit",compact('recipes','kitchens'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'title'=>'required | max:50 |min:5 ',
            ]
              ) ;
              if($request->hasfile('images'))
              {
               $file=$request->file('images');
              $images=$this->uploadimages($file,"images");

              }
              else
              {
                $images="no-images.png";
              }

            $recipes= recipe::find($id);
            $recipes->name=$request->title;
            $recipes->About=$request->About;
            $recipes->image=$images;
            $recipes->video=$request->video;
            $recipes->ingredients=$request->ingredients;
            $recipes->direction=$request->direction;
            $recipes->kitchen_id=$request->kitchen_id;
            $recipes->save();
            return redirect()->route('recipes.index')->withmsg('post saved sucessfully');
    }
    public function uploadimages($images,$dir)
{
  $file=$images;

  $images_name=$file->getClientOriginalName();//name.jpg
  $ext=$file->getClientOriginalExtension();//jpg
  $images='images/'.time().$images_name;

  $file->move($dir,$images);
  return $images;
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $recipes=recipe::find($id);
    $recipes->delete();
    return redirect()->route('recipes.index')->withmsg('recipes deleted');

    }
}

resources/views/backend/recipes/create.blade.php
@extends('layouts.app');

@section("title","recipes")




@section("content")
<div class="container">



        <div class="row">

        <form method="post" action="{{url('/recipes')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title">
                <label for="exampleFormControlTextarea1" >About</label>
                <textarea class="form-control" name="about" rows="3"></textarea>
                <label for="exampleFormControlTextarea1" >ingredients</label>
                <textarea class="form-control" name="ingredients" rows="3"></textarea>
               <label for="exampleFormControlTextarea1" >direction</label>
                <textarea class="form-control" name="direction" rows="3"></textarea>
                <label for="exampleFormControlSlect2" >Url video</label>
                <input class="form-control" name="video">
                <label for="exampleFormControlSlect2">Kitchen</label>
                <label for="exampleFormControlTextarea1">image</label>
            <input type="file" name="image">

                <div class="form-select">
                    <select name="kitchen_id" class="form-select btn-secondary dropdown-toggle" aria-label="Default select example">
                      @foreach ($kitchens as $kitchen)

                      <option value="{{$kitchen->id}}">
                        {{$kitchen->name}}
                      </option>

                      @endforeach

                    </select>
                </div>
              </div>

              <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>


@endsection

resources/views/backend/recipes/edit.blade.php
@extends('layouts.app');

@section("title","recipes")




@section("content")
<div class="container">

        <div class="row">

        <form method="post" action="{{ route('recipes.update',$recipes->id)}}" enctype="multipart/form-data">


            @csrf @method("put")



<div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title" value="{{$recipes->name}}">
                <label for="exampleFormControlTextarea1" >about</label>
                <input class="form-control" name="About" rows="3" value="{{$recipes->About}}">
                <label for="exampleFormControlTextarea1" >ingredients</label>
                <input class="form-control" name="ingredients" rows="3" value="{{$recipes->ingredients}}">
                <label for="exampleFormControlTextarea1" >direction</label>
                <input class="form-control" name="direction" rows="3" value="{{$recipes->direction}}">
                <label for="exampleFormControlSlect2" >Url video</label>
                <input class="form-control" name="video" value="{{$recipes->video}}">
                <label for="exampleFormControlTextarea1">image</label>
                <input type="file" name="images"><br>
                <label for="exampleFormControlSlect2">Kitchen</label>
                <div class="form-select">
                    <select name="kitchen_id" class="form-select btn-secondary dropdown-toggle" aria-label="Default select example">
                      @foreach ($kitchens as $kitchen)

                      <option value="{{$kitchen->id}}">
                        {{$kitchen->name}}
                      </option>

                      @endforeach

                    </select>
                </div>
              </div>


        <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>


@endsection

resources/views/backend/recipes/index.blade.php
@extends('layouts.app');

@section("title","recipes")




@section("content")
<div class="container">


     <div class="container-fluid">
      <a href="recipes/create/">Add New Recipes</a>
        <div class="row">

        @foreach ( $recipes as $recipes )

        <div class="card col-md-3" style="width: 30rem;">
            <div class="card-body">
              <h5 class="card-title"><a href="recipes/{{$recipes->id}}">{{$recipes->title}}</a></h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$recipes->name}}</h6>
              {{-- <a href="recipes/{{$recipes->ingredients}}">ingredients</a> --}}
              {{-- <p class="card-text">{{$recipes->image}}</p> --}}
              <img src="{{asset(''.$recipes->image)}}" class=w-50 ><br>

              @auth
        <a class="btn btn-primary" href="recipes/{{$recipes->id}}/edit" class="card-link" style="color: white">Edit</a>

  <form method="post" action="recipes/{{$recipes->id}}">

      @csrf @method("delete")
      <button type='submit' class="btn btn-danger">Delete</button>
  </form>
  @endauth
            </div>
          </div>



     @endforeach

        </div>
     </div>
</div>


@endsection

resources/views/backend/recipes/show.blade.php
@extends('layouts.app');

@section("title","recipes")




@section("content")
<div class="container">





        <div class="row">

        <div class="card col-md-12" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{$recipes->title}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$recipes->id}}</h6>
              <p class="card-text">{{$recipes->name}}</p>
              <p class="card-text">{{$recipes->About}}</p>
              <p class="card-text">{{$recipes->ingredients}}</p>
              <p class="card-text">{{$recipes->direction}}</p>
              <p class="card-text">{{$recipes->video}}</p>
              <p class="card-text">{{$recipes->kitchen_id}}</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
</div>

@endsection