routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard','dashboardController@index');
// Route::get('/kitchen','KitchenController@index');
Route::resource('kitchens', 'KitchenController');
Route::resource('restaurants', 'RestaurantController');
Route::resource('recipes', 'RecipeController');
Route::get('home','homeController@index');
Route::get('kitchen/{id}','kitchen_controller@kitchen')->name('kitchen');
Route::get('recipe/{id}','kitchen_controller@recipe')->name('recipe');
Route::post('search','homecontroller@search')->name('search');

Auth::routes();

app/kitchen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use app\restaurant;
class kitchen extends Model
{

  public $timestamps=false;
    public function restaurant()
    {
        return $this->hasMany('App\restaurant');
    }
}
 

app/Http/Controllers/kitchenController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\kitchen;

class kitchencontroller extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $kitchens = kitchen::paginate(6);
        $kitchens=kitchen::all();
       return view ('backend.kitchens.index',compact('kitchens'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("backend.kitchens.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'title'=>'required',

                'img'=>'required|image|mimes:jpeg,png,jpg,gif,webp'
            ]
              ) ;
             if($request->hasfile('img'))
             {
              $file=$request->file('img');
             $img=$this->uploadImg($file,"img/kitchens");

             }
             else
             {
               $img="no-image.png";
             }
            $kitchen=new kitchen();
            $kitchen->name=$request->title;
            $kitchen->img=$img;

            // $post->user_id=Auth::user()->id;
            $kitchen->save();

            // return redirect()->back();

            return redirect()->route('kitchens.index')->withmsg('post saved sucessfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kitchen=kitchen::find($id);
     return view("backend.kitchens.show",compact("kitchen"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kitchen=kitchen::find($id);
      return view("backend.kitchens.edit",compact('kitchen'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
                'title'=>'required | max:50 |min:5 ',
                'img'=>'required|image|mimes:jpeg,png,jpg,gif,webp|max:2048'
            ]
              ) ;
              if($request->hasfile('img'))
              {
               $file=$request->file('img');
              $img=$this->uploadImg($file,"img/kitchens");

              }
              else
              {
                $img="no-image.png";
              }

            $kitchen= kitchen::find($id);
            $kitchen->name=$request->title;
            $kitchen->img=$img;
             $kitchen->save();
            return redirect()->route('kitchens.index')->withmsg('post saved sucessfully');
    }
    public function uploadImg($img,$dir)
{
  $file=$img;

  $img_name=$file->getClientOriginalName();//name.jpg
  $ext=$file->getClientOriginalExtension();//jpg
  $image=time().$img_name;

  $file->move($dir,$image);
  return $image;
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kitchen=kitchen::find($id);
    $kitchen->delete();
    return redirect()->route('kitchens.index')->withmsg('kitchen deleted');

    }
}

app/Http/Controllers/kitchen_controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class kitchen_controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function index()
    // {
    //     return view("frontend.kitchen");

    // }

    public function kitchen($id)

    {
        $kitchens=\App\kitchen::all();
        $kitchen=\App\kitchen::find($id);
        $recipes=\App\recipe::where("kitchen_id",$id)->get();
        $restaurants=\App\restaurant::where("kitchen_id",$id)->get();
        return view("frontend.kitchen",compact("recipes","restaurants","kitchen","kitchens"));
        
    }
    public function recipe($id)

    {
        // $kitchen=\App\recipe::find($id);
        // dd($kitchen);
        $kitchens=\App\kitchen::all();
        $recipe=\App\recipe::find($id);
        //  $restaurants=\App\restaurant::where("kitchen_id",$recipe->kitchen_id)->get();
        $restaurants=\App\kitchen::find($recipe->kitchen_id)->restaurant;
        // dd($restaurant);
        return view("frontend.recipe",compact("restaurants","recipe","kitchens"));
        
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
}

resources/views/backend/kitchens/create.blade.php
@extends('layouts.app');

@section("title","kitchens")



   
@section("content")
<div class="container">

         
  
        <div class="row">
    
        <form method="post" action="{{url('/kitchens')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title">
              </div>
              {{-- <div class="form-group">
                <label for="exampleFormControlTextarea1" >Content</label>
                <textarea class="form-control" name="content" rows="3"></textarea>
              </div> --}}
    <label for="exampleFormControlTextarea1">image</label>
    <input type="file" name="img">
        <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>

    
@endsection

resources/views/backend/kitchens/edit.blade.php
@extends('layouts.app');

@section("title","kitchens")




@section("content")
<div class="container">

        <div class="row">

        <form method="post" action="{{ route('kitchens.update',$kitchen->id)}}" enctype="multipart/form-data">


            @csrf @method("put")
            <div class="form-group">
                <label for="exampleFormControlSlect2" >name</label>
                <input class="form-control" name="title" value="{{$kitchen->name}}">
              </div>
              <label for="exampleFormControlTextarea1">image</label>
              <input type="file" name="img">

        <input type="submit" class="btn btn-primary">
        </form>
        </div>
</div>


@endsection

resources/views/backend/kitchens/index.blade.php
@extends('layouts.app');

@section("title","kitchens")




@section("content")
<div class="container">


     <div class="container-fluid">
      <a href="kitchens/create/">Add New Kitchen</a>
        <div class="row">

        @foreach ( $kitchens as $kitchen )

        <div class="card col-md-3" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><a href="kitchens/{{$kitchen->id}}">{{$kitchen->title}}</a></h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$kitchen->name}}</h6>
              <p class="card-text">{{$kitchen->img}}</p>
              <img src="{{asset('img/kitchens/'.$kitchen->img)}}" class=w-100 >
              @auth
              <a class="btn btn-primary" href="kitchens/{{$kitchen->id}}/edit" class="card-link">Edit</a>
  <form method="post" action="kitchens/{{$kitchen->id}}">

      @csrf @method("delete")
      <button type='submit' class="btn btn-danger">Delete</button>
  </form>
  @endauth
            </div>
          </div>



     @endforeach

        </div>
     </div>
</div>


@endsection

resources/views/backend/kitchens/show.blade.php
@extends('layouts.app');

@section("title","kitchens")



   
@section("content")
<div class="container">

      
    
   
  
        <div class="row">
    
        <div class="card col-md-12" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{$kitchen->title}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{$kitchen->id}}</h6>
              <p class="card-text">{{$kitchen->name}}</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
            
        
    
 
     
        </div>
</div>

    
@endsection